import 'package:app/api/todo_models.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('TodoStatus', () {
    // The kanban board's _boardColumnDefs (todos_page.dart) is generated by
    // iterating TodoStatus.values directly — there's no separate ordering
    // list to fall out of sync, so locking in the enum's declaration order
    // here is equivalent to locking in the board's 8-column order
    // (Triage/Backlog/Todo/In Progress/In Review/Done/Canceled/Duplicate,
    // matching Linear's own layout with Triage as the "待分诊" inbox).
    test('declaration order is the Linear board column order', () {
      expect(TodoStatus.values, [
        TodoStatus.triage,
        TodoStatus.backlog,
        TodoStatus.todo,
        TodoStatus.inProgress,
        TodoStatus.inReview,
        TodoStatus.done,
        TodoStatus.canceled,
        TodoStatus.duplicate,
      ]);
    });

    test('todoStatusName/todoStatusFromName round-trip for all 8 values', () {
      for (final s in TodoStatus.values) {
        expect(todoStatusFromName(todoStatusName(s)), s);
      }
    });

    test('wire names match pkg/todoschema.Status exactly', () {
      expect(todoStatusName(TodoStatus.triage), 'triage');
      expect(todoStatusName(TodoStatus.backlog), 'backlog');
      expect(todoStatusName(TodoStatus.todo), 'todo');
      expect(todoStatusName(TodoStatus.inProgress), 'in_progress');
      expect(todoStatusName(TodoStatus.inReview), 'in_review');
      expect(todoStatusName(TodoStatus.done), 'done');
      expect(todoStatusName(TodoStatus.canceled), 'canceled');
      expect(todoStatusName(TodoStatus.duplicate), 'duplicate');
    });

    test('unknown/legacy wire values fall back to todo, not a crash', () {
      // 'pending'/'assigned'/'blocked'/'cancelled' were the pre-taxonomy-
      // rework 6-value spellings — the relay migrates stored rows, but a
      // stale client-side cache or a malformed payload should still degrade
      // gracefully instead of throwing.
      expect(todoStatusFromName('pending'), TodoStatus.todo);
      expect(todoStatusFromName('assigned'), TodoStatus.todo);
      expect(todoStatusFromName('blocked'), TodoStatus.todo);
      expect(todoStatusFromName('cancelled'), TodoStatus.todo);
      expect(todoStatusFromName(null), TodoStatus.todo);
      expect(todoStatusFromName('made-up'), TodoStatus.todo);
    });
  });

  group('Todo.fromJson group_name', () {
    Map<String, dynamic> baseJson({dynamic groupName = _omit}) {
      final j = <String, dynamic>{
        'id': 'x1',
        'project_id': null,
        'owner_identity': 'alice',
        'title': 't',
        'body_md': '',
        'status': 'todo',
        'priority': 'normal',
        'assignee_identity': null,
        'assignee_session_id': null,
        'assignee_session_label': null,
        'recurrence': '',
        'due_at': null,
        'next_occurrence_at': null,
        'completed_at': null,
        'created_at': '2026-01-01T00:00:00Z',
        'updated_at': '2026-01-01T00:00:00Z',
        'comment_count': 0,
        'attachment_count': 0,
      };
      if (!identical(groupName, _omit)) j['group_name'] = groupName;
      return j;
    }

    test('round-trips a non-empty group name', () {
      final t = Todo.fromJson(baseJson(groupName: '我的日常'));
      expect(t.groupName, '我的日常');
    });

    test('absent group_name key parses to null', () {
      final t = Todo.fromJson(baseJson());
      expect(t.groupName, isNull);
    });

    test('empty-string group_name parses to null (ungrouped)', () {
      final t = Todo.fromJson(baseJson(groupName: ''));
      expect(t.groupName, isNull);
    });

    test('copyWith preserves groupName', () {
      final t = Todo.fromJson(baseJson(groupName: 'sprint-1'));
      final copy = t.copyWith();
      expect(copy.groupName, 'sprint-1');
    });
  });
}

// _omit is a sentinel distinguishing "caller didn't pass groupName at all"
// from "caller explicitly passed null" — a plain `dynamic groupName` default
// of `null` can't tell those apart, and the whole point of one of these
// tests is that the JSON key itself can be absent.
const _omit = Object();
